version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: stcfilemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

  your-application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stcfilemanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD:
